# .github/workflows/build.yml
name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        uses: uggi0501/buildozer-action@v1
        with:
          buildozer-version: stable
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
